tuiter/urls.py
"""tuiter URL Configuration."""

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from tuiter import settings

from tuits import urls as tuiter_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include(tuiter_urls, namespace='tuiter'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # NOQA

tuits/urls.py
"""Urls for tuits."""

from django.conf.urls import url

from .views import tuits

urlpatterns = [
    url(r'^$', tuits.landingPageView, name='landing'),
    url(r'login$', tuits.tuiter_login, name='login'),
    url(r'register$', tuits.register, name='register'),
    url(r'logout$', tuits.tuiter_logout, name='logout'),
    url(r'timeline$', tuits.timeline, name='timeline'),
    url(r'newtuit$', tuits.newtuit, name='newtuit'),
    url(r'search_user$', tuits.searchUser, name='searchUser'),
    url(r'my_profile$', tuits.my_profile, name='my_profile'),
    url(r'edit_profile$', tuits.edit_profile, name='edit_profile'),
    url(r'edit_basic_info$', tuits.editBasicInfo, name='editBasicInfo'),
    url(r'change_password$', tuits.changePassword, name='changePassword'),
    url(r'delete_tuit$', tuits.deleteTuit, name='deleteTuit'),
    url(r'like_tuit$', tuits.likeTuit, name='likeTuit'),
    url(r'remove_tuit_like$', tuits.removeTuitLike, name='removeTuitLike'),
    url(r'retuit$', tuits.retuit, name='retuit'),
    url(
        r'user_profile/(?P<tuiter_username>[\w-]+)',
        tuits.userProfile,
        name='userProfile'
        ),
    url(
        r'user_follow/(?P<tuiter_user>[\w-]+)',
        tuits.userFollow,
        name='userFollow'
        ),
    url(
        r'user_unfollow/(?P<tuiter_user>[\w-]+)',
        tuits.userUnfollow,
        name='userUnfollow'
        ),
    url(
        r'user_following/(?P<tuiter_username>[\w-]+)',
        tuits.userProfileFollowing,
        name='userProfileFollowing'
        ),
    url(
        r'user_followers/(?P<tuiter_username>[\w-]+)',
        tuits.userProfileFollowers,
        name='userProfileFollowers'
        ),
    url(
        r'upload_profile_image$',
        tuits.uploadProfileImage,
        name='uploadProfileImage'
        ),
    url(
        r'upload_cover_image$',
        tuits.uploadCoverImage,
        name='uploadCoverImage'
        ),
    url(
        r'tuit_detail/(?P<tuit_id>[\d-]+)',
        tuits.tuitDetail,
        name='tuitDetail'
        ),
]

tuits/models.py
"""Models for tuits app."""

from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User


class Tuit(models.Model):
    """Model for tuit."""

    def tuit_file_name(instance, filename):
        """Rename tuit file function."""
        ext = filename.split('.')[-1]
        file_path = 'media/tuits/images/' + instance.user.username + '_' + str(instance.id) + '.' + ext  # NOQA
        return file_path

    def video_file_name(instance, filename):
        """Rename tuit file function."""
        ext = filename.split('.')[-1]
        file_path = 'media/tuits/videos/' + instance.user.username + '_' + str(instance.id) + '.' + ext  # NOQA
        return file_path

    user = models.ForeignKey(User)
    message = models.TextField(blank=False, null=False)
    tuit_date = models.DateTimeField(auto_now_add=True)
    picture = models.ImageField(
        upload_to=tuit_file_name,
        blank=True,
        null=True
    )
    video_file = models.FileField(
        upload_to=video_file_name, max_length=200, blank=True, null=True
    )
    total_likes = models.IntegerField(default=0)
    total_retuits = models.IntegerField(default=0)

    is_retuit = models.BooleanField(default=False)
    original_tuit = models.ForeignKey(
        "Tuit",
        related_name='retuited_tuit',
        blank=True,
        null=True
    )

    def __str__(self):
        """Return tuit."""
        return "{user} tuited {message}...".format(
            user=self.user.username,
            message=self.message[:10]
        )


class UserLikesTuit(models.Model):
    """Model for user likes tuit."""

    user = models.ForeignKey(User, blank=False, null=False)
    tuit = models.ForeignKey(Tuit, blank=False, null=False)
    like_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return user likes tuit."""
        return "{user} liked tuit {message}...".format(
            user=self.user.username,
            message=self.tuit.message[:10]
        )

tuits/views.py
from django.shortcuts import render

# Create your views here.

tuits/views/tuits.py
"""Teams Views module."""

from django.views import generic
from ..models import Tuit, UserLikesTuit
from useraccounts.models import UserSettings, UserFollowsUser
from django.contrib.auth.models import User
from django.db.models import Q

from django.views.generic import (
    TemplateView,
)

from django.shortcuts import get_object_or_404, render
from django.http import (
    HttpResponseRedirect,
    HttpResponse,
    HttpResponseNotFound
    )
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse

from django.shortcuts import render_to_response, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
import json
import ast


def landingPageView(request):
    """function for landing view."""
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('tuiter:timeline'))
    else:
        return render_to_response(
            'account/landing.html',
            context_instance=RequestContext(request)
        )


def tuiter_login(request):
    """login function."""
    logout(request)
    username = password = ''
    ctxt = None
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('tuiter:timeline'))
        else:
            ctxt = {
                'loginMessage': 'Wrong username or password'
            }
    return render_to_response(
            'account/landing.html',
            context=ctxt,
            context_instance=RequestContext(request)
        )


def tuiter_logout(request):
    """logout funciton."""
    logout(request)
    return render_to_response(
            'account/landing.html',
            context_instance=RequestContext(request)
        )


def timeline(request):
    """timeline function."""
    ctxt = None
    username = None
    if request.user.is_authenticated():
        user = request.user
        username = request.user.username
        followed_users = UserFollowsUser.objects.filter(
                user=user
            )
        followed_users_ids = []
        for u in followed_users:
            followed_users_ids.append(u.followed_user.id)
        followed_users_ids.append(user.id)
        timeline_tuits = Tuit.objects.filter(
            user__in=followed_users_ids,
        ).order_by('-tuit_date')
        user_likes_tuits = UserLikesTuit.objects.filter(user=user)
        tuits = []
        for t in timeline_tuits:
            tuit_data = {
                'tuit_object': t,
                'liked': False
            }
            for ult in user_likes_tuits:
                if t == ult.tuit:
                    tuit_data['liked'] = True
                    break
            tuits.append(tuit_data)
        redirect_url = 'tuiter:timeline'
        ctxt = {
            'timeline_tuits': tuits,
            'username': username,
            'logged_user': user,
            'redirect_url': redirect_url,
            'use_parameters': False,
            'public_access': False
        }
        return render_to_response(
                'tuits/timeline.html',
                context=ctxt,
                context_instance=RequestContext(request)
            )
    else:
        return render_to_response(
            'account/landing.html',
            context_instance=RequestContext(request)
            )


def newtuit(request):
    """newtuit funciton."""
    tuit_text = ''
    tuit_picture = None
    if request.POST:
        tuit_text = request.POST['tuit_text']
        try:
            tuit_picture = request.FILES['fileToUpload']
        except:
            tuit_picture = None
    if tuit_text and len(tuit_text) > 0 and request.user.is_authenticated():
        user = request.user
        newT = Tuit()
        newT.user = user
        newT.message = tuit_text
        if tuit_picture:
            newT.picture = tuit_picture
        newT.save()
    return HttpResponseRedirect(reverse('tuiter:timeline'))


def my_profile(request):
    """my_profile funciton."""
    public_access = False
    if request.user.is_authenticated():
        user = request.user
        user_settings = UserSettings.objects.filter(
                user=user
            )[0]
        timeline_tuits = Tuit.objects.filter(
                user=user,
            ).order_by('-tuit_date')
        total_tuits = len(Tuit.objects.filter(
                user=user
            ))
        total_following = len(UserFollowsUser.objects.filter(
                user=user
            ))
        total_followers = len(UserFollowsUser.objects.filter(
                followed_user=user
            ))
        user_likes_tuits = UserLikesTuit.objects.filter(user=user)
        tuits = []
        for t in timeline_tuits:
            tuit_data = {
                'tuit_object': t,
                'liked': False
            }
            for ult in user_likes_tuits:
                if t == ult.tuit:
                    tuit_data['liked'] = True
                    break
            tuits.append(tuit_data)
        redirect_url = 'tuiter:my_profile'
        if user.is_anonymous():
            public_access = True
        ctxt = {
            'timeline_tuits': tuits,
            'user': user,
            'user_settings': user_settings,
            'total_tuits': total_tuits,
            'total_following': total_following,
            'total_followers': total_followers,
            'logged_user': user,
            'redirect_url': redirect_url,
            'use_parameters': False,
            'public_access': public_access
        }
        return render_to_response(
            'account/my_profile.html',
            context=ctxt,
            context_instance=RequestContext(request)
            )
    else:
        return render_to_response(
            'account/landing.html',
            context_instance=RequestContext(request)
            )


def edit_profile(request):
    """Edit profile function."""
    if request.user.is_authenticated():
        user = request.user
        user_settings = UserSettings.objects.filter(
                user=user
            )[0]
        ctxt = {
            'user': user,
            'user_settings': user_settings
        }
        return render_to_response(
            'account/edit_profile.html',
            context=ctxt,
            context_instance=RequestContext(request)
            )
    else:
        return render_to_response(
            'account/landing.html',
            context_instance=RequestContext(request)
            )


def register(request):
    """Register function."""
    ctxt = user = username = email = password = None
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        email = request.POST['email']
        users = User.objects.filter(
                username=username
            )
        if users:
            ctxt = {
                'registerMessage': "Username already exists."
            }
            return render_to_response(
                'account/landing.html',
                context=ctxt,
                context_instance=RequestContext(request)
            )
        elif password != confirm_password:
            ctxt = {
                'registerMessage': "The password doesn't match."
            }
            return render_to_response(
                'account/landing.html',
                context=ctxt,
                context_instance=RequestContext(request)
            )
        elif len(password) == 0:
            ctxt = {
                'registerMessage': "The password is empty."
            }
            return render_to_response(
                'account/landing.html',
                context=ctxt,
                context_instance=RequestContext(request)
            )
        else:
            user = User()
            user.username = username
            user.email = email
            user.set_password(password)
            user.save()
            user_settings = UserSettings()
            user_settings.user = user
            user_settings.save()
            user_log_in = authenticate(
                username=username,
                password=password
                )
            if user_log_in is not None:
                if user_log_in.is_active:
                    login(request, user_log_in)
                    return HttpResponseRedirect(reverse('tuiter:timeline'))


def editBasicInfo(request):
    """Edit basic info function."""
    user = new_first_name = new_last_name = new_email = None
    if request.POST:
        new_first_name = request.POST['first_name']
        new_last_name = request.POST['last_name']
        new_email = request.POST['email']
        if request.user.is_authenticated():
            user = request.user
            user.first_name = new_first_name
            user.last_name = new_last_name
            user.email = new_email
            user.save()
            user_settings = UserSettings.objects.get(user=user)
            ctxt = {
                'userUpdated': 'yes',
                'user': user,
                'user_settings': user_settings

            }
            return render_to_response(
                    'account/edit_profile.html',
                    context=ctxt,
                    context_instance=RequestContext(request)
                )
        else:
            return render_to_response(
                'account/landing.html',
                context_instance=RequestContext(request)
                )
    else:
        return render_to_response(
                'account/edit_profile.html',
                context_instance=RequestContext(request)
            )


def changePassword(request):

templates/tuits/navigation_bar.html
<ul style="list-style-type:none">
    {% if not user.is_anonymous %}
    <li><a href="{% url 'tuiter:timeline' %}">Timeline</a></li>
    <li><a href="{% url 'tuiter:my_profile' %}">Profile</a></li>
    <li><a href="{% url 'tuiter:logout' %}">Logout</a></li>
    {% else %}
    <li><a href="{% url 'tuiter:landing' %}">Tuiter</a></li>
    {% endif %}
</ul>

templates/tuits/new_tuit.html
<aside>
    <form action="{% url 'tuiter:newtuit' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <ul style="list-style-type:none">
            <li><textarea name="tuit_text" rows="3" cols="50"></textarea></li>
            <li><input type="file" name="fileToUpload" id="fileToUpload" name="Add Image"><input type="submit" value="Tuit"></li>
        </ul>
    </form>
</aside>

templates/tuits/timeline.html
{% extends "tuits/tuiter_base.html" %}
{% block title %}Timeline{% endblock %}
{% block body %}
    <h3> Timeline de {{ username }} </h3>
    {% include "tuits/new_tuit.html" %}
    {% include "account/user_search.html" %}
    {% include "tuits/tuits_list.html" %}
{% endblock %}

templates/tuits/tuit_card.html
<article>
    <ul style="list-style-type:none">
        {% if tuit_object.is_retuit == True %}
        <li><a href="{% url 'tuiter:userProfile' tuit_object.user.username %}">{{ tuit_object.user.username }}</a> retuited: </li>
        <li><a href="{% url 'tuiter:userProfile' tuit_object.original_tuit.user.username %}">@{{ tuit_object.original_tuit.user.username }}</a> {{ tuit_object.tuit_date | date:"g:i  d M, Y" }} </li>
        {% else %}
        <li><a href="{% url 'tuiter:userProfile' tuit_object.user.username %}">@{{ tuit_object.user.username }}</a> {{ tuit_object.tuit_date | date:"g:i  d M, Y" }} </li>
        {% endif %}
        <li><a href="{% url 'tuiter:tuitDetail' tuit_object.id %}" style="text-decoration: none; color : #000000;">{{ tuit_object.message }}</a></li>
        {% if tuit_object.picture %}
        <li>
            <figure>
                <img src="{{ tuit_object.picture.url }}" alt="tuit_picture" height="150" width="150">
            </figure>
        </li>
        {% endif %}
        <table>
            <tr>
                <td>likes {{ tuit_object.total_likes }}</td>
                {% if tuit_object.is_retuit == True %}
                <td>retuits {{ tuit_object.original_tuit.total_retuits }}</td>
                {% else %}
                <td>retuits {{ tuit_object.total_retuits }}</td>
                {% endif %}
            </tr>
        </table>
        <li>
        {% if public_access == False %}
        <table>
            <tr>
                <td>
                    {% if tuit_liked == True %}
                    <form action="{% url 'tuiter:removeTuitLike' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="tuit_id" value="{{ tuit_object.id }}">
                        <input type="hidden" name="redirect_url" value="{{ redirect_url }}">
                        <input type="hidden" name="use_parameters" value="{{ use_parameters }}">
                        <input type="hidden" name="parameter_name" value="{{ parameter_name }}">
                        <input type="hidden" name="parameter_value" value="{{ parameter_value }}">
                        <input id="{{ tuit_object.id }}" type="submit" value="Dislike">
                    </form>
                    {% else %}
                    <form action="{% url 'tuiter:likeTuit' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="tuit_id" value="{{ tuit_object.id }}">
                        <input type="hidden" name="redirect_url" value="{{ redirect_url }}">
                        <input type="hidden" name="use_parameters" value="{{ use_parameters }}">
                        <input type="hidden" name="parameter_name" value="{{ parameter_name }}">
                        <input type="hidden" name="parameter_value" value="{{ parameter_value }}">
                        <input id="{{ tuit_object.id }}" type="submit" value="Like">
                    </form>
                    {% endif %}
                </td>
                <td>
                    <form action="{% url 'tuiter:retuit' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="tuit_id" value="{{ tuit_object.id }}">
                        <input type="hidden" name="redirect_url" value="{{ redirect_url }}">
                        <input type="hidden" name="use_parameters" value="{{ use_parameters }}">
                        <input type="hidden" name="parameter_name" value="{{ parameter_name }}">
                        <input type="hidden" name="parameter_value" value="{{ parameter_value }}">
                        <input type="submit" value="Retuit">
                    </form>
                </td>
                {% if logged_user.username == tuit_object.user.username %}
                <td>
                    <form action="{% url 'tuiter:deleteTuit' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="tuit_id" value="{{ tuit_object.id }}">
                        <input type="hidden" name="redirect_url" value="{{ redirect_url }}">
                        <input type="hidden" name="use_parameters" value="{{ use_parameters }}">
                        <input type="hidden" name="parameter_name" value="{{ parameter_name }}">
                        <input type="hidden" name="parameter_value" value="{{ parameter_value }}">
                        <input type="submit" value="Delete">
                    </form>
                </td>
                {% endif %}
            </tr>
        </table>
        {% endif %}
        </li>
        <li>&nbsp;</li>
    </ul>
</li>
</article>

templates/tuits/tuit_detail.html
{% extends "tuits/tuiter_base.html" %}
{% block title %}Tuit Detail{% endblock %}
{% block body %}
    {% include "tuits/tuit_card.html" %}
{% endblock %}

templates/tuits/tuiter_base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static from staticfiles %}
    <meta charset="UTF-8" />
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}"/>
    <!-- Stylesheets -->
    {% block css_plugins %}{% endblock %}
    <!-- Scripts -->
    {% block js_plugins %}{% endblock %}
</head>
<body>
    {% include "tuits/navigation_bar.html" %}
    {% block body %}{% endblock %}
    {% block body_scripts %}{% endblock %}
</body>
</html>

templates/tuits/tuits_list.html
<article>
    <ul style="list-style-type:none">
        {% for t in timeline_tuits %}
            <li>
                <ul style="list-style-type:none">
                    {% if t.tuit_object.is_retuit == True %}
                    <li><a href="{% url 'tuiter:userProfile' t.tuit_object.user.username %}">{{ t.tuit_object.user.username }}</a> retuited: </li>
                    <li><a href="{% url 'tuiter:userProfile' t.tuit_object.original_tuit.user.username %}">@{{ t.tuit_object.original_tuit.user.username }}</a> {{ t.tuit_object.tuit_date | date:"g:i  d M, Y" }} </li>
                    {% else %}
                    <li><a href="{% url 'tuiter:userProfile' t.tuit_object.user.username %}">@{{ t.tuit_object.user.username }}</a> {{ t.tuit_object.tuit_date | date:"g:i  d M, Y" }} </li>
                    {% endif %}
                    <li><a href="{% url 'tuiter:tuitDetail' t.tuit_object.id %}" style="text-decoration: none; color : #000000;">{{ t.tuit_object.message }}</a></li>
                    {% if t.tuit_object.picture %}
                    <li>
                        <figure>
                            <img src="{{ t.tuit_object.picture.url }}" alt="tuit_picture" height="150" width="150">
                        </figure>
                    </li>
                    {% endif %}
                    <table>
                        <tr>
                            <td>likes {{ t.tuit_object.total_likes }}</td>
                            {% if t.tuit_object.is_retuit == True %}
                            <td>retuits {{ t.tuit_object.original_tuit.total_retuits }}</td>
                            {% else %}
                            <td>retuits {{ t.tuit_object.total_retuits }}</td>
                            {% endif %}
                        </tr>
                    </table>
                    <li>
                    {% if public_access == False %}
                    <table>
                        <tr>
                            <td>
                                {% if t.liked == True %}
                                <form action="{% url 'tuiter:removeTuitLike' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="tuit_id" value="{{ t.tuit_object.id }}">
                                    <input type="hidden" name="redirect_url" value="{{ redirect_url }}">
                                    <input type="hidden" name="use_parameters" value="{{ use_parameters }}">
                                    <input type="hidden" name="parameter_name" value="{{ parameter_name }}">
                                    <input type="hidden" name="parameter_value" value="{{ parameter_value }}">
                                    <input id="{{ t.tuit_object.id }}" type="submit" value="Dislike">
                                </form>
                                {% else %}
                                <form action="{% url 'tuiter:likeTuit' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="tuit_id" value="{{ t.tuit_object.id }}">
                                    <input type="hidden" name="redirect_url" value="{{ redirect_url }}">
                                    <input type="hidden" name="use_parameters" value="{{ use_parameters }}">
                                    <input type="hidden" name="parameter_name" value="{{ parameter_name }}">
                                    <input type="hidden" name="parameter_value" value="{{ parameter_value }}">
                                    <input id="{{ t.tuit_object.id }}" type="submit" value="Like">
                                </form>
                                {% endif %}
                            </td>
                            <td>
                                <form action="{% url 'tuiter:retuit' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="tuit_id" value="{{ t.tuit_object.id }}">
                                    <input type="hidden" name="redirect_url" value="{{ redirect_url }}">
                                    <input type="hidden" name="use_parameters" value="{{ use_parameters }}">
                                    <input type="hidden" name="parameter_name" value="{{ parameter_name }}">
                                    <input type="hidden" name="parameter_value" value="{{ parameter_value }}">
                                    <input type="submit" value="Retuit">
                                </form>
                            </td>
                            {% if logged_user.username == t.tuit_object.user.username %}
                            <td>
                                <form action="{% url 'tuiter:deleteTuit' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="tuit_id" value="{{ t.tuit_object.id }}">
                                    <input type="hidden" name="redirect_url" value="{{ redirect_url }}">
                                    <input type="hidden" name="use_parameters" value="{{ use_parameters }}">
                                    <input type="hidden" name="parameter_name" value="{{ parameter_name }}">
                                    <input type="hidden" name="parameter_value" value="{{ parameter_value }}">
                                    <input type="submit" value="Delete">
                                </form>
                            </td>
                            {% endif %}
                        </tr>
                    </table>
                    {% endif %}
                    </li>
                    <li>&nbsp;</li>
                </ul>
            </li>
        {% empty %}
            <p>No hay tuits</p>
        {% endfor %}
    </ul>
</article>